import Head from 'next/head'
import Footer from './Footer';
import Navbar from './Navbar';

const Layout = ({ title = 'DeviTools', children }) => {
    return (
        <>
            <Head>
                <title>DeviTools | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <section >
                <main>
                    {children}
                </main>
            </section>
            <Footer/>
        </>
    )
}

export default Layout;