import Head from 'next/head'
import Aside from './Aside';
import Footer from './Footer';
import Navbar from './Navbar';

const Layout = ({ title = 'DeviTools', children }) => {
    return (
        <>
            <Head>
                <title>DeviTools | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex'>
                <Aside />
                <div className='w-full'>
                    <Navbar />
                    <section>
                        <main>
                            {children}
                        </main>
                    </section>
                </div>
            </div>
            <Footer />
        </>
    )
}

export default Layout;